# Generated by Django 5.2.4 on 2026-07-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage_color_name_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color_name',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_image',
            field=models.ImageField(blank=True, null=True, upload_to='variant_colors/'),
        ),
    ]
