# Generated by Django 5.2.4 on 2026-07-15 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_wishlist', '0001_initial'),
        ('products', '0004_replace_color_fields_with_color_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='products.productvariant'),
        ),
    ]
