# Generated by Django 5.2.4 on 2026-07-16 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_promotion', '0001_initial'),
        ('products', '0004_replace_color_fields_with_color_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='products.category'),
        ),
        migrations.AddField(
            model_name='banner',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage shown on this banner (e.g. 20 for 20%)', max_digits=5, null=True),
        ),
    ]
