# Generated by Django 5.2.4 on 2026-07-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_stock_deducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Stripe Payment Intent ID or Razorpay Payment ID', max_length=255, null=True),
        ),
    ]
